"""
Used for demo purposes.
Clean the files made by DemoAudioSplit.py to show during demo that
DemoAudioSplit.py works as intended and splits .wav files
"""

import os
import glob

# dirs: directory where the files to train the SVM are located
dirs = ["speakers/Amy/splits/", "speakers/Scott/splits/", "speakers/Matthew/splits/"]
# testDirs: directory where the files to test the SVM are located
testDirs = ["speakers/Amy/filesToTest/splits/", "speakers/Scott/filesToTest/splits/",
            "speakers/Matthew/filesToTest/splits/"]


# function for deleting files generated by DemoAudioSplit.py
def pruneFolder(d):
    file = glob.glob(d + "*.wav")
    # print("\nTest files: ", file)  # test prints
    for f in file:
         os.remove(f)  # remove the file if it is not one of the protected files


# clean training files
for d in dirs:
    pruneFolder(d)  # remove extra files in dirs directories

# clean test files
for d in testDirs:
    pruneFolder(d)  # remove extra files in testDirs directories
