"""
Used for demo purposes.
Clean the files made by DemoAudioSplit.py to show during demo that
DemoAudioSplit.py works as intended and splits .wav files
"""

import os
import glob

# dirs: directory where the files to train the SVM are located
dirsOrig = ["speakers/Amy/splits1/", "speakers/Matthew/splits1/", "speakers/Scott/splits1/"]
# testDirs: directory where the files to test the SVM are located
testDirs = []

for root, dirs, files in os.walk("speakers/filesToTest/"):
    for name in dirs:
        testDirs.append("speakers/filesToTest/" + name + "/")


def pruneDir(dirs1):
    os.rmdir(dirs1)


# print("Test dirs: ", testDirs)

# function for deleting files generated by DemoAudioSplit.py
def pruneFolder(d):
    file = glob.glob(d + "*.wav")
    # print("\nTest files: ", file)  # test prints
    for f in file:
        os.remove(f)  # remove the file if it is not one of the protected files


# clean training files
for d in dirsOrig:
    pruneFolder(d)  # remove extra files in dirs directories
    pruneDir(d)

# clean test files
for d in testDirs:
    pruneFolder(d)  # remove extra files in testDirs directories
    pruneDir(d)
